### ISSUE TITLE
[Provider] Add support for AI21 models

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/gateway#12]
Docs: https://docs.ai21.com/reference/j2-complete-api-ref

**Comment by kritikash18** [comment]
Hi @vrushankportkey, can I please work on this issue if its available?

**Comment by vrushankportkey** [comment]
Thank you, @kritikash18  - assigned to you. 

Cheers!

**Comment by kritikash18** [comment]
@vrushankportkey just wanted to confirm if there is any baseline for the APIs that need to be supported since the API types for AI21 are different than regular chat, complete and embedding APIs as AI21 provides specific service APIs instead. 
APIs offered:

complete API
datasets APIs (get/delete)
custom model APIs (training/get/complete/epoch)
tokenize API 
task-specific APIs - (paraphrase/grammatical error corrections/ summarize, ..etc)

do I need to support a fixed subset or all?

**Comment by VisargD** [comment]
Hey. You can start with the complete API. Structure for adding a new provider can be seen under https://github.com/Portkey-AI/Rubeus/tree/main/src/providers. Please let me know if you have any doubts once you go through the code.

**Comment by kritikash18** [comment]
Raised #21

**Comment by VisargD** [comment]
Thanks @kritikash18 . Will take a look into this

**Comment by vrushankportkey** [comment]
Thank you for raising the PR so quickly, @kritikash18 ⚡ 

Are you there on the [Portkey discord](https://discord.gg/tmnpp4pqzv)?

**Comment by kritikash18** [comment]
Hi, joined now...the username is bytecode_bc
