### ISSUE TITLE
YAML vs JSON Configuration Management

### ISSUE THREAD

**Issue by ranjancse26** [Portkey-AI/gateway#141]
I think it's a good idea to consider the YAML based configuration management, as it's human-readable, easy for all kinds of users to understand. JSON is great, however, it's a just a thought to consider having YAML as well.

**Comment by ayush-portkey** [comment]
Hi @ranjancse26,

Thank you for bringing up this point!

Our decision to use JSON instead of YAML was primarily influenced by our team's familiarity and comfort with JSON. You're right that both formats have their merits. JSON, known for its simplicity and wide compatibility, has served our needs well so far.

However, we recognize that YAML has its advantages too, particularly in terms of readability. While we're currently focused on maintaining a single format for simplicity, we're certainly open to the idea of incorporating YAML in the future. This would be especially considered if it brings significant benefits or if there's a clear demand from our user community.

Hope this helps. Closing this issue for now.
