### ISSUE TITLE
Error with Azure OpenAI virtual key setup

### ISSUE THREAD

**Issue by nlpravi** [Portkey-AI/gateway#160]
I'm trying to add AzureOpenAI Virtual key. Getting "Error: Something wrong. Please try again"

I'm entering the API key, Azure deployment name, Resource name (Endpoint URL), and Azure API version. 

Thank you, 
Ravi.

**Comment by vrushankportkey** [comment]
@nlpravi confirming that this should work. Would it be possible to share the code snippet you are using to make the call?

**Comment by nlpravi** [comment]
This is happening during the creation of virtual key in the dashboard. I'm not using any code here.

**Comment by VisargD** [comment]
Hey @nlpravi - This usually happens due to incorrect azure details or incorrect format of azure details. As you mentioned in your message that you are entering resource url which is incorrect. You just need to add resource name and not the whole url. Example: If `abc` is my resource name under which I created a deployment named turbo-16k and I want to use 2023-09-01-preview version
Resource name: abc
Deployment name: turbo-16k
API Version: 2023-09-01-preview

Can you please use this format for details and let us know if you still face this error

**Comment by nlpravi** [comment]
Thank you Visarg. It works now.

**Comment by VisargD** [comment]
Great..!! We will add some detailed steps for this in our docs to avoid confusion in future. Closing this issue. Feel free to open a new one in case you have other questions.
