### ISSUE TITLE
Azure openai does not support encoding format

### ISSUE THREAD

**Issue by narengogi** [Portkey-AI/gateway#745]
### What Happened?

azure openai transform does not support encoding_format input param

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added the encoding_format parameter to the AzureOpenAIChatCompleteConfig and AzureOpenAICompleteConfig objects to support this input in Azure OpenAI transformations.

You can review changes in this commit: https://github.com/lattaai11/Portkey-AI-gateway-745/commit/8d40c26272a8925bef5db3e5d1710e2beeddbbbc.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added the encoding_format parameter to the AzureOpenAIChatCompleteConfig and AzureOpenAICompleteConfig objects. Updated the response transform functions to handle the encoding_format in the response.

You can review changes in this commit: https://github.com/lattaai11/Portkey-AI-gateway-745/commit/58a1f3b4213433e535fe646a645da2c647b91e06.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
